
language: node_js
node_js:
  - "10"
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - server/node_modules
install:
  - cd server
  - npm install
  - npm run build
script:
  - cd server
  - nohup npm run start &
  - sleep 3
  - npm run test